version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./image_files:/image_files
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=images
  web:
    build: .
    command: bash -c "pip3 install -r requirements.txt &&
                      apt-get update && apt-get -y install cron && python3 manage.py makemigrations &&
                      python3 manage.py migrate && python3 manage.py crontab add &&
                      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
