# Generated by Django 3.2.6 on 2021-11-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sha1', models.CharField(max_length=40)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'image_data',
            },
        ),
    ]
